/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth */
        post: operations["auth_auth_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Insights */
        post: operations["insights_search_insights_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tenders */
        get: operations["tenders_tenders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{doc_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tender */
        get: operations["tender_tenders__doc_no__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{doc_no}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tender For Profile */
        post: operations["tender_for_profile_tenders__doc_no__detail_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{doc_no}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Overview */
        post: operations["overview_tenders__doc_no__overview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenders/{doc_no}/checklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Checklist */
        post: operations["checklist_tenders__doc_no__checklist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eligibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Eligibility */
        post: operations["eligibility_eligibility_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/awards/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Similar Awards */
        get: operations["similar_awards_awards_similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/licences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Licences */
        get: operations["licences_licences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/licences/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Licences */
        get: operations["search_licences_licences_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Files */
        get: operations["session_files_sessions__session_id__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/files/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session File */
        get: operations["session_file_sessions__session_id__files__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory */
        get: operations["memory_sessions__session_id__memory_get"];
        put?: never;
        /** Remember */
        post: operations["remember_sessions__session_id__memory_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/memory/{note_id}/forget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forget */
        post: operations["forget_sessions__session_id__memory__note_id__forget_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_sessions__session_id__uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthRequest */
        AuthRequest: {
            /** Code */
            code: string;
        };
        /** AuthResponse */
        AuthResponse: {
            /** Token */
            token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** AwardExample */
        AwardExample: {
            /** Tender No */
            tender_no: string;
            /** Description */
            description: string;
            /** Agency */
            agency: string;
            /** Year */
            year: number | null;
            /** Amount */
            amount: number | null;
            /** Suppliers */
            suppliers: string[];
        };
        /** BcaWorkhead */
        BcaWorkhead: {
            /**
             * Code
             * @example CW01
             */
            code: string;
            /**
             * Grade
             * @example B2
             */
            grade?: string | null;
        };
        /**
         * BidMemory
         * @description What a bid session remembers across turns and sandboxes: notes, and where the bid stands.
         */
        BidMemory: {
            /**
             * Notes
             * @default []
             */
            notes: components["schemas"]["MemoryNote"][];
            /** Stage */
            stage?: ("qualify" | "clarify" | "draft" | "review" | "submit") | null;
            /** Next Step */
            next_step?: string | null;
            /** Updated */
            updated?: string | null;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** Session Id */
            session_id?: string | null;
            profile: components["schemas"]["Profile"];
            /**
             * Doc No
             * @description The tender the conversation is about, if any
             */
            doc_no?: string | null;
            /**
             * Bid
             * @description A bid session: the copilot works the bid on doc_no, with a bid memory
             * @default false
             */
            bid: boolean;
            /**
             * Autopilot
             * @description With bid: take the next step of the bid without stopping to ask the person
             * @default false
             */
            autopilot: boolean;
        };
        /** ChecklistItem */
        ChecklistItem: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Source
             * @enum {string}
             */
            source: "notice" | "eligibility" | "drafting" | "submission";
            /** Due */
            due?: string | null;
        };
        /** EligibilityCheck */
        EligibilityCheck: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "closing" | "gra" | "bca" | "licence" | "value" | "company";
            /** Requirement */
            requirement: string;
            status: components["schemas"]["EligibilityStatus"];
            /** Reason */
            reason: string;
            /** Source Url */
            source_url?: string | null;
        };
        /** EligibilityRequest */
        EligibilityRequest: {
            /** Doc No */
            doc_no: string;
            profile: components["schemas"]["Profile"];
        };
        /**
         * EligibilityStatus
         * @enum {string}
         */
        EligibilityStatus: "met" | "unmet" | "unknown";
        /** EligibilitySummary */
        EligibilitySummary: {
            /** Met */
            met: number;
            /** Unmet */
            unmet: number;
            /** Unknown */
            unknown: number;
            /** @description The first unmet check */
            blocker?: components["schemas"]["EligibilityCheck"] | null;
            /** @description The first unknown check */
            open_question?: components["schemas"]["EligibilityCheck"] | null;
        };
        /** Fit */
        Fit: {
            /** Score */
            score: number;
            recommendation: components["schemas"]["Recommendation"];
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
        };
        /**
         * GraHead
         * @description A GRA (EPU) supply head a notice requires, with the tendering capacity it names.
         */
        GraHead: {
            /**
             * Code
             * @example EPU/CMP/10
             */
            code: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Capacity Sgd
             * @description Tendering capacity named on the notice, e.g. 250000
             */
            capacity_sgd?: number | null;
            /**
             * Grade
             * @example S3
             */
            grade?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InsightsRequest */
        InsightsRequest: {
            /** Doc Nos */
            doc_nos: string[];
            profile: components["schemas"]["Profile"];
            /**
             * Query
             * @description The search the cards came from, for the snippet
             */
            query?: string | null;
        };
        /** KeyDate */
        KeyDate: {
            /** Label */
            label: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /** Licence */
        Licence: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Agency */
            agency: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Who Needs It
             * @default
             */
            who_needs_it: string;
            /**
             * Fee
             * @default
             */
            fee: string;
            /**
             * Processing Time
             * @default
             */
            processing_time: string;
            /**
             * Validity
             * @default
             */
            validity: string;
            /**
             * Prerequisites
             * @default []
             */
            prerequisites: string[];
            /** Url */
            url: string;
        };
        /** MarketBand */
        MarketBand: {
            /** Similar Count */
            similar_count: number;
            /** Median Amount */
            median_amount: number | null;
            /** P25 Amount */
            p25_amount: number | null;
            /** P75 Amount */
            p75_amount: number | null;
        };
        /** MarketContext */
        MarketContext: {
            /** Similar Count */
            similar_count: number;
            /** Median Amount */
            median_amount: number | null;
            /** P25 Amount */
            p25_amount: number | null;
            /** P75 Amount */
            p75_amount: number | null;
            /** Top Suppliers */
            top_suppliers: components["schemas"]["SupplierWins"][];
            /** Agency Incumbents */
            agency_incumbents: components["schemas"]["SupplierWins"][];
            /** No Award Share */
            no_award_share: number | null;
            /** Examples */
            examples: components["schemas"]["AwardExample"][];
        };
        /** MemoryNote */
        MemoryNote: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /**
             * Source
             * @enum {string}
             */
            source: "kopi" | "you";
            /**
             * Created
             * Format: date-time
             */
            created: string;
        };
        /** MemoryRequest */
        MemoryRequest: {
            /** Text */
            text: string;
        };
        /**
         * Notice
         * @description One GeBIZ opportunity. Contact persons are never part of it.
         */
        Notice: {
            /** Doc No */
            doc_no: string;
            /**
             * Type
             * @example Quotation
             * @example Tender
             * @example Tender Lite
             */
            type: string;
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Agency */
            agency: string;
            /**
             * Published
             * Format: date-time
             */
            published: string;
            /**
             * Closing
             * Format: date-time
             */
            closing: string;
            /** @default open */
            status: components["schemas"]["NoticeStatus"];
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Procurement Type
             * @default
             */
            procurement_type: string;
            /**
             * Procurement Method
             * @default
             */
            procurement_method: string;
            /**
             * Procurement Nature
             * @default
             */
            procurement_nature: string;
            /** Two Envelope */
            two_envelope?: boolean | null;
            /** Wto Gpa */
            wto_gpa?: boolean | null;
            /**
             * Gra Heads
             * @default []
             */
            gra_heads: components["schemas"]["GraHead"][];
            /**
             * Bca Workheads
             * @default []
             */
            bca_workheads: components["schemas"]["BcaWorkhead"][];
            /**
             * Licences Mentioned
             * @default []
             */
            licences_mentioned: string[];
            /**
             * Items
             * @default []
             */
            items: string[];
            /**
             * Delivery Location
             * @default
             */
            delivery_location: string;
            /** Url */
            url: string;
            /**
             * Source
             * @default live
             * @enum {string}
             */
            source: "live" | "fixture";
        };
        /**
         * NoticeStatus
         * @enum {string}
         */
        NoticeStatus: "open" | "closed" | "awarded" | "cancelled";
        /**
         * NoticeSummary
         * @description The listing view of a notice.
         */
        NoticeSummary: {
            /** Doc No */
            doc_no: string;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Agency */
            agency: string;
            /**
             * Published
             * Format: date-time
             */
            published: string;
            /**
             * Closing
             * Format: date-time
             */
            closing: string;
            status: components["schemas"]["NoticeStatus"];
            /** Category */
            category: string;
            /** Url */
            url: string;
        };
        /** Overview */
        Overview: {
            /** Doc No */
            doc_no: string;
            /** Profile Id */
            profile_id: string;
            /** Summary */
            summary: string;
            /** Buying */
            buying: string;
            /** Who Can Bid */
            who_can_bid: string;
            fit: components["schemas"]["Fit"];
            /**
             * Key Dates
             * @default []
             */
            key_dates: components["schemas"]["KeyDate"][];
            /**
             * Risks
             * @default []
             */
            risks: string[];
            /**
             * Questions For Agency
             * @default []
             */
            questions_for_agency: string[];
            /**
             * Unverified Quotes
             * @default 0
             */
            unverified_quotes: number;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** OverviewRequest */
        OverviewRequest: {
            profile: components["schemas"]["Profile"];
        };
        /**
         * Profile
         * @description The company Kopi works for. `None` means "we do not know", never "no".
         */
        Profile: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Uen */
            uen?: string | null;
            /** Summary */
            summary: string;
            /**
             * Capabilities
             * @default []
             */
            capabilities: string[];
            /**
             * Past Work
             * @default []
             */
            past_work: string[];
            /** Gra Registrations */
            gra_registrations?: components["schemas"]["Registration"][] | null;
            /** Bca Registrations */
            bca_registrations?: components["schemas"]["Registration"][] | null;
            /** Licences Held */
            licences_held?: string[] | null;
            /** Bizsafe Level */
            bizsafe_level?: string | null;
            /** @default {} */
            value_band_sgd: components["schemas"]["ValueBand"];
        };
        /** Reason */
        Reason: {
            /** Point */
            point: string;
            /**
             * Quote
             * @description Verbatim text from the notice or profile
             */
            quote: string;
            /**
             * Verified
             * @default false
             */
            verified: boolean;
            /**
             * Found In
             * @description Where code found the quote word for word; None when it wasn't found
             */
            found_in?: ("notice" | "profile") | null;
        };
        /**
         * Recommendation
         * @enum {string}
         */
        Recommendation: "BID" | "MAYBE" | "NO_BID";
        /**
         * Registration
         * @description A registration the company holds: a GRA supply head or a BCA workhead, with grade.
         */
        Registration: {
            /** Code */
            code: string;
            /** Grade */
            grade?: string | null;
            /** Expires */
            expires?: string | null;
        };
        /** SearchHit */
        SearchHit: {
            notice: components["schemas"]["NoticeSummary"];
            /**
             * Score
             * @description 0..1, higher is closer
             */
            score: number;
            /**
             * Highlights
             * @default []
             */
            highlights: string[];
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Total */
            total: number;
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
        };
        /** SessionFile */
        SessionFile: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Size */
            size: number;
            /**
             * Modified
             * Format: date-time
             */
            modified: string;
            /**
             * Kind
             * @default draft
             * @enum {string}
             */
            kind: "draft" | "upload";
        };
        /** SupplierWins */
        SupplierWins: {
            /** Supplier */
            supplier: string;
            /** Wins */
            wins: number;
        };
        /** TenderDetail */
        TenderDetail: {
            notice: components["schemas"]["Notice"];
            /** Eligibility */
            eligibility: components["schemas"]["EligibilityCheck"][];
            market: components["schemas"]["MarketContext"] | null;
        };
        /**
         * TenderInsight
         * @description What a search card shows beyond the summary, for one company profile.
         */
        TenderInsight: {
            /** Doc No */
            doc_no: string;
            eligibility: components["schemas"]["EligibilitySummary"];
            /**
             * Snippet
             * @description The description sentence closest to the query, at most 240 characters
             */
            snippet?: string | null;
            /** Items */
            items: number;
            /** Two Envelope */
            two_envelope?: boolean | null;
            /** Procurement Method */
            procurement_method?: string | null;
            market?: components["schemas"]["MarketBand"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValueBand */
        ValueBand: {
            /** Min Sgd */
            min_sgd?: number | null;
            /** Max Sgd */
            max_sgd?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    auth_auth_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
                status?: components["schemas"]["NoticeStatus"] | null;
                agency?: string | null;
                category?: string | null;
                method?: string | null;
                closing_after?: string | null;
                closing_before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insights_search_insights_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InsightsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderInsight"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tenders_tenders_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: components["schemas"]["NoticeStatus"] | null;
                agency?: string | null;
                category?: string | null;
                method?: string | null;
                closing_after?: string | null;
                closing_before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoticeSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tender_tenders__doc_no__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_no: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tender_for_profile_tenders__doc_no__detail_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_no: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_tenders__doc_no__overview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_no: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checklist_tenders__doc_no__checklist_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_no: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eligibility_eligibility_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EligibilityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EligibilityCheck"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_awards_awards_similar_get: {
        parameters: {
            query: {
                q: string;
                agency?: string | null;
                k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    licences_licences_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Licence"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_licences_licences_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Licence"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description ChatEvent per SSE message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_files_sessions__session_id__files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionFile"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_file_sessions__session_id__files__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_sessions__session_id__memory_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidMemory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remember_sessions__session_id__memory_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidMemory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forget_sessions__session_id__memory__note_id__forget_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BidMemory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_sessions__session_id__uploads_post: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionFile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
